### ISSUE TITLE
Ability to associate WAF with Cloudfront

### ISSUE THREAD

**Issue by rajcheval** [cloudposse/terraform-aws-cloudfront-cdn#15]
I wanted to associate a global AWS WAF ACL with CloudFront. I did not find an option to pass in existing WAF.
Typically I get around this by using null provisioners and executing aws cli.
I took a quick look and I did not see an option to associate a global WAF ACL with CloudFront using CLI.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-cloudfront-cdn/pull/16
