### ISSUE TITLE
Use ordered_cache_behavior instead of cache_behavior as it is deprecated

### ISSUE THREAD

**Issue by rajpolaris** [cloudposse/terraform-aws-cloudfront-cdn#18]
Warning: module.cdn.aws_cloudfront_distribution.default: "cache_behavior": [DEPRECATED] Use `ordered_cache_behavior` instead

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-cloudfront-cdn/pull/22
